name: CD - Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  workflow_dispatch:


jobs:
  build:
    name: Build binaries
    runs-on: ${{ matrix.os }}
    permissions:
          contents: read
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64
            extension: ''
          - os: macos-latest
            platform: darwin
            arch: x64
            extension: ''
          - os: macos-latest
            platform: darwin
            arch: arm64
            extension: ''
          - os: windows-latest
            platform: win32
            arch: x64
            extension: '.exe'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.17'

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Create bin directory
        run: mkdir -p bin

      - name: Build binary
        run: bun build --compile --minify --sourcemap src/index.ts --outfile bin/lsh${{ matrix.extension }}

      - name: Make binary executable (Unix)
        if: matrix.os != 'windows-latest'
        run: chmod +x bin/lsh

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: lsh-${{ matrix.platform }}-${{ matrix.arch }}
          path: bin/lsh${{ matrix.extension }}

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for tags on current commit
        id: check_tag
        run: |
          # Get all tags pointing to the current commit
          TAGS=$(git tag --points-at HEAD)
          if [ -n "$TAGS" ]; then
            # Get the first tag (in case there are multiple)
            TAG=$(echo "$TAGS" | head -n1)
            echo "has_tag=true" >> $GITHUB_OUTPUT
            echo "tag_name=$TAG" >> $GITHUB_OUTPUT
            echo "Found tag: $TAG"
          else
            echo "has_tag=false" >> $GITHUB_OUTPUT
            echo "No tags found on current commit"
          fi

      - name: Download all artifacts
        if: steps.check_tag.outputs.has_tag == 'true'
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Extract version from tag
        if: steps.check_tag.outputs.has_tag == 'true'
        id: version
        run: echo "version=${{ steps.check_tag.outputs.tag_name }}" >> $GITHUB_OUTPUT

      - name: Prepare release assets
        if: steps.check_tag.outputs.has_tag == 'true'
        run: |
          mkdir -p release
          # Rename and move binaries with proper names
          mv artifacts/lsh-linux-x64/lsh release/lsh-linux-x64
          mv artifacts/lsh-darwin-x64/lsh release/lsh-darwin-x64
          mv artifacts/lsh-darwin-arm64/lsh release/lsh-darwin-arm64
          mv artifacts/lsh-win32-x64/lsh.exe release/lsh-win32-x64.exe
          
          # Create checksums
          cd release
          sha256sum lsh-* > checksums.txt
          ls -la

      - name: Create Release
        if: steps.check_tag.outputs.has_tag == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          body: |
            ## LazyShell ${{ steps.version.outputs.version }}
            
            ### Downloads
            - **Linux (x64)**: `lsh-linux-x64`
            - **macOS (x64)**: `lsh-darwin-x64`
            - **macOS (ARM64)**: `lsh-darwin-arm64`
            - **Windows (x64)**: `lsh-win32-x64.exe`
            
            ### Installation
            1. Download the appropriate binary for your platform
            2. Make it executable: `chmod +x lsh-*` (Unix systems)
            3. Move to a directory in your PATH: `mv lsh-* /usr/local/bin/lsh`
            4. Run: `lsh --help`
            
            ### Checksums
            SHA256 checksums are included in `checksums.txt` for verification.
          files: |
            release/lsh-linux-x64
            release/lsh-darwin-x64
            release/lsh-darwin-arm64
            release/lsh-win32-x64.exe
            release/checksums.txt
          draft: false
          prerelease: ${{ contains(steps.version.outputs.version, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

