name: CI

on:
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'src/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.17'

      - name: Install dependencies
        run: bun install --frozen-lockfile

          
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 23
      #     cache: 'bun'
          
      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint
        
      - name: Build project
        run: bun run build
        
      # - name: Run tests
      #   run: pnpm test

  # Summary job that requires both test and evals to pass
  ci-check:
    runs-on: ubuntu-latest
    needs: [test]
    if: always()
    
    steps:
      - name: Check CI results
        run: |
          if [[ "${{ needs.test.result }}" == "skipped" ]]; then
            echo "⚠️  Tests skipped (missing API keys)"
          elif [[ "${{ needs.test.result }}" != "success" ]]; then
            echo "❌ Tests failed"
            exit 1
          else
            echo "✅ CI passed (tests)"
          fi 
